DBhomework/DBHW/urls.py
from django.urls import path,re_path,include
from DBHW.views import *
app_name = 'DBHW'
urlpatterns = [
    re_path(r'^nationlist/',Nation_list,name='nationlist'),
    re_path(r'^nationedit-(?P<nid>\d+)/',Nation_Edit,name='nationedit'),
    re_path(r'^nationadd/',Nation_add,name='nationadd'),
    re_path(r'^nationview-(?P<nid>\d+)/',Nation_view,name='nationview'),
    re_path(r'^nationdelete-(?P<nid>\d+)/',Nation_delete,name='nationdelete'),
    re_path(r'^customerlist/', Customer_list, name='customerlist'),
    re_path(r'^customersearch/',Customer_search,name='customersearch'),
    re_path(r'^regionsearch/',Region_search,name='regionsearch'),
    re_path(r'^partsearch/', Part_search, name='partsearch'),
    re_path(r'^nationsearch/', Nation_search, name='nationsearch'),
    re_path(r'^suppliersearch/', Supplier_search, name='suppliersearch'),
    re_path(r'^customeredit-(?P<nid>\d+)/', Customer_Edit, name='customeredit'),
    re_path(r'^customeradd/', Customer_add, name='customeradd'),
    re_path(r'^customerview-(?P<nid>\d+)/', Customer_view, name='customerview'),
    re_path(r'^customerdelete-(?P<nid>\d+)/', Customer_delete, name='customerdelete'),
    re_path(r'^lineitemlist/', Lineitem_list, name='lineitemlist'),
    re_path(r'^lineitemedit-(?P<nid>\d+)-(?P<uid>\d+)/',Lineitem_Edit, name='lineitemedit'),
    re_path(r'^lineitemadd/', Lineitem_Add, name='lineitemadd'),
    re_path(r'^lineitemview-(?P<nid>\d+)-(?P<uid>\d+)/', Lineitem_view, name='lineitemview'),
    re_path(r'^lineitemdelete-(?P<nid>\d+)-(?P<uid>\d+)/', Lineitem_delete, name='lineitemdelete'),
    re_path(r'^orderlist/', Order_list, name='orderlist'),
    re_path(r'^orderview-(?P<nid>\d+)/', Order_view, name='orderview'),
    re_path(r'^orderdelete-(?P<nid>\d+)/', Order_delete, name='orderdelete'),
    re_path(r'^orderadd/', Order_Add, name='orderadd'),
    re_path(r'^partlist/', Part_list, name='partlist'),
    re_path(r'^partedit-(?P<nid>\d+)/', Part_Edit, name='partedit'),
    re_path(r'^partadd/', Part_Add, name='partadd'),
    re_path(r'^partview-(?P<nid>\d+)/', Part_view, name='partview'),
    re_path(r'^partdelete-(?P<nid>\d+)/',Part_delete, name='partdelete'),
    re_path(r'^partsupplist/', Partsupp_list, name='partsupplist'),
    re_path(r'^partsuppedit-(?P<nid>\d+)-(?P<uid>\d+)/', Partsupp_Edit, name='partsuppedit'),
    re_path(r'^partsuppadd/', Partsupp_Add, name='partsuppadd'),
    re_path(r'^partsuppview-(?P<nid>\d+)-(?P<uid>\d+)/', Partsupp_view, name='partsuppview'),
    re_path(r'^partsuppdelete-(?P<nid>\d+)-(?P<uid>\d+)/',Partsupp_delete, name='partsuppdelete'),
    re_path(r'^regionlist/', Region_list, name='regionlist'),
    re_path(r'^regionedit-(?P<nid>\d+)/', Region_Edit, name='regionedit'),
    re_path(r'^regionadd/', Region_Add, name='regionadd'),
    re_path(r'^regionview-(?P<nid>\d+)/', Region_view, name='regionview'),
    re_path(r'^regiondelete-(?P<nid>\d+)/', Region_delete, name='regiondelete'),
    re_path(r'^supplierlist/', Supplier_list, name='supplierlist'),
    re_path(r'^supplieredit-(?P<nid>\d+)/', Supplier_Edit, name='supplieredit'),
    re_path(r'^supplieradd/', Supplier_Add, name='supplieradd'),
    re_path(r'^supplierview-(?P<nid>\d+)/', Supplier_view, name='supplierview'),
    re_path(r'^supplierdelete-(?P<nid>\d+)/', Supplier_delete, name='supplierdelete'),
 ]

DBhomework/DBhomework/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from DBHW.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
  #前面是正则表达式
    re_path(r'^DBHW/',include('DBHW.urls',namespace='DBHW')),
 ]

DBhomework/templates/customerlist.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{%static '/css/ie10-viewport-bug-workaround.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{%static '/css/dashboard.css'%}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{%static '/js/ie-emulation-modes-warning.js'%}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">TPC-H</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../customerlist">顾客</a></li>
            <li><a href="../partlist">零件</a></li>
            <li><a href="../orderlist">订单</a></li>
            <li><a href="../supplierlist">供应商</a></li>
            <li><a href="../lineitemlist">订单明细</a></li>
            <li><a href="../partsupplist">零件供应</a></li>
             <li><a href="../nationlist">国家</a></li>
            <li><a href="../regionlist">地区</a></li>
          </ul>
          <form class="navbar-form navbar-right" method="get" action="{% url 'DBHW:customersearch' %}">
            <input type="text" class="form-control"  name="name" placeholder="Search...">
          </form>

        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">表单： <span class="sr-only">(current)</span></a></li>
            <li><a href="{% url 'DBHW:customerlist'  %}">顾客</a></li>
            <li><a href="{% url 'DBHW:partlist'  %}">零件</a></li>
            <li><a href="{% url 'DBHW:supplierlist'  %}">供应商</a></li>
            <li><a href="{% url 'DBHW:partsupplist'  %}">零件供应</a></li>
            <li><a href="{% url 'DBHW:orderlist'  %}">订单</a></li>
            <li><a href="{% url 'DBHW:nationlist'  %}">国家</a></li>
            <li><a href="{% url 'DBHW:regionlist'  %}">地区</a></li>
            <li><a href="{% url 'DBHW:lineitemlist'  %}">订单明细</a></li>
          </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">顾客</h1>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>顾客编号</th>
                  <th>顾客名称</th>
                  <th>顾客地址</th>
                  <th>所属国家</th>
                  <th>联系电话</th>
                  <th>可用余额</th>
                  <th>市场</th>
                  <th>备注</th>
                </tr>
              </thead>
              <tbody>
                  <a href="{% url 'DBHW:customeradd' %}" >
                  <button class="btn btn-success">增加</button></a>
              {% for item in customer_list %}
                <tr>
                  <td>{{ item.c_custkey }}</td>
                  <td>{{ item.c_name }}</td>
                  <td>{{ item.c_address }}</td>
                  <td>{{ item.c_nationkey.n_name }}</td>
                  <td>{{ item.c_phone}}</td>
                  <td>{{ item.c_acctbal }}</td>
                  <td>{{ item.c_mktsegment }}</td>
                  <td>{{ item.c_comment }}</td>

                <td>

                  <a href="{% url 'DBHW:customeredit' item.c_custkey  %}" id="{{ item.c_custkey }}">
                  <button class="btn btn-success">编辑</button></a>
                   <a href="{% url 'DBHW:customerdelete' item.c_custkey  %}" id="{{ item.c_custkey }}">
                  <button class="btn btn-success">删除</button></a>

                   <a href="{% url 'DBHW:customerview' item.c_custkey%}" id="{{ item.c_custkey }}">
                  <button class="btn btn-success">浏览</button></a>
                  </td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>

      <ul class="pager">
        <li>
        {% if customer_list.has_previous %}
            <a href="?page={{ customer_list.previous_page_number }}">上一页</a>
        {% else %}
            <a> 第一页 </a>
        {% endif %}
        </li>

        <span class="text-primary">
             第{{ customer_list.number }}页   共{{ customer_list.paginator.num_pages }}页
        </span>

        <li>
        {% if customer_list.has_next %}
            <a href="?page={{ customer_list.next_page_number }}">下一页</a>
        {% else %}
            <a> 最后一页 </a>
        {% endif %}

        </li>
      </ul>

      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

DBhomework/templates/regionlist.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{%static '/css/ie10-viewport-bug-workaround.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{%static '/css/dashboard.css'%}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{%static '/js/ie-emulation-modes-warning.js'%}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">TPC-H</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../customerlist">顾客</a></li>
            <li><a href="../partlist">零件</a></li>
            <li><a href="../orderlist">订单</a></li>
            <li><a href="../supplierlist">供应商</a></li>
            <li><a href="../lineitemlist">订单明细</a></li>
            <li><a href="../partsupplist">零件供应</a></li>
             <li><a href="../nationlist">国家</a></li>
            <li><a href="../regionlist">地区</a></li>
          </ul>
          <form class="navbar-form navbar-right" method="get" action="{% url 'DBHW:regionsearch' %}">
            <input type="text" class="form-control"  name="name" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
  <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">表单： <span class="sr-only">(current)</span></a></li>
            <li><a href="{% url 'DBHW:customerlist'  %}">顾客</a></li>
            <li><a href="{% url 'DBHW:partlist'  %}">零件</a></li>
            <li><a href="{% url 'DBHW:supplierlist'  %}">供应商</a></li>
            <li><a href="{% url 'DBHW:partsupplist'  %}">零件供应</a></li>
            <li><a href="{% url 'DBHW:orderlist'  %}">订单</a></li>
            <li><a href="{% url 'DBHW:nationlist'  %}">国家</a></li>
            <li><a href="{% url 'DBHW:regionlist'  %}">地区</a></li>
            <li><a href="{% url 'DBHW:lineitemlist'  %}">订单明细</a></li>
          </ul>

        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">地区</h1>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>地区编号</th>
                  <th>地区名称</th>
                  <th>备注</th>
                  <th>供应价格</th>
                    <th>备注</th>
                </tr>
              </thead>
              <tbody>
                  <a href="{% url 'DBHW:regionadd' %}">
                  <button class="btn btn-success">增加</button></a>
              {% for item in region_list %}
                <tr>
                  <td>{{ item.r_regionkey }}</td>
                  <td>{{ item.r_name }}</td>
                  <td>{{ item.r_comment }}</td>
                    <td>{{ item.ps_supplycost }}</td>
                    <td>{{ item.ps_comment }}</td>
                    <td>
                  <a href="{% url 'DBHW:regionedit' item.r_regionkey  %}" id="{{ item.r_regionkey }}">
                  <button class="btn btn-success">编辑</button></a>
                   <a href="{% url 'DBHW:regiondelete' item.r_regionkey  %}" id="{{ item.r_regionkey }}">
                  <button class="btn btn-success">删除</button></a>
                   <a href="{% url 'DBHW:regionview' item.r_regionkey%}" id="{{ item.r_regionkey }}">
                  <button class="btn btn-success">浏览</button></a>
                  </td>
                </tr>
              {% endfor %}

              </tbody>
            </table>
          </div>
        </div>
      <ul class="pager">
        <li>
        {%if region_list.has_previous %}
            <a href="?page={{ region_list.previous_page_number }}">上一页</a>
        {% else %}
            <a> 第一页 </a>
        {% endif %}
        </li>

        <span class="text-primary">
             第{{ region_list.number }}页   共{{ region_list.paginator.num_pages }}页
        </span>

        <li>
        {% if region_list.has_next %}
            <a href="?page={{ region_list.next_page_number }}">下一页</a>
        {% else %}
            <a> 最后一页 </a>
        {% endif %}

        </li>
      </ul>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

DBhomework/templates/supplierlist.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Dashboard Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{%static '/css/ie10-viewport-bug-workaround.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{%static '/css/dashboard.css'%}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{%static '/js/ie-emulation-modes-warning.js'%}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">TPC-H</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../customerlist">顾客</a></li>
            <li><a href="../partlist">零件</a></li>
            <li><a href="../orderlist">订单</a></li>
            <li><a href="../supplierlist">供应商</a></li>
            <li><a href="../lineitemlist">订单明细</a></li>
            <li><a href="../partsupplist">零件供应</a></li>
             <li><a href="../nationlist">国家</a></li>
            <li><a href="../regionlist">地区</a></li>
          </ul>
          <form class="navbar-form navbar-right" method="get" action="{% url 'DBHW:suppliersearch' %}">
            <input type="text" class="form-control"  name="name" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>


    <div class="container-fluid">
      <div class="row">
 <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">表单： <span class="sr-only">(current)</span></a></li>
            <li><a href="{% url 'DBHW:customerlist'  %}">顾客</a></li>
            <li><a href="{% url 'DBHW:partlist'  %}">零件</a></li>
            <li><a href="{% url 'DBHW:supplierlist'  %}">供应商</a></li>
            <li><a href="{% url 'DBHW:partsupplist'  %}">零件供应</a></li>
            <li><a href="{% url 'DBHW:orderlist'  %}">订单</a></li>
            <li><a href="{% url 'DBHW:nationlist'  %}">国家</a></li>
            <li><a href="{% url 'DBHW:regionlist'  %}">地区</a></li>
            <li><a href="{% url 'DBHW:lineitemlist'  %}">订单明细</a></li>
          </ul>

        </div>        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">供应商</h1>
          <div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>供应商编号</th>
                  <th>供应商名称</th>
                  <th>供应商地址</th>
                  <th>所属国家</th>
                    <th>电话 </th>
                    <th>账户余额</th>
                    <th>备注</th>
                </tr>
              </thead>
              <tbody>
                  <a href="{% url 'DBHW:supplieradd' %}" >
                  <button class="btn btn-success">增加</button></a>
              {% for item in supplier_list %}
                <tr>
                  <td>{{ item.s_suppkey }}</td>
                  <td>{{ item.s_name }}</td>
                  <td>{{ item.s_address }}</td>
                    <td>{{ item.s_nationkey.n_name }}</td>
                    <td>{{ item.s_phone }}</td>
                    <td>{{ item.s_acctbal }}</td>
                    <td>{{ item.s_comment }}</td>
                    <td>
                  <a href="{% url 'DBHW:supplieredit' item.s_suppkey %}" id="{{ item.s_suppkey }}">
                  <button class="btn btn-success">编辑</button></a>
                   <a href="{% url 'DBHW:supplierdelete' item.s_suppkey  %}" id="{{ item.s_suppkey }}">
                  <button class="btn btn-success">删除</button></a>
                   <a href="{% url 'DBHW:supplierview' item.s_suppkey%}" id="{{ item.s_suppkey }}">
                  <button class="btn btn-success">浏览</button></a>
                  </td>
                </tr>
              {% endfor %}

              </tbody>
            </table>
          </div>
        </div>
      <ul class="pager">
        <li>
        {%if supplier_list.has_previous %}
            <a href="?page={{ supplier_list.previous_page_number }}">上一页</a>
        {% else %}
            <a> 第一页 </a>
        {% endif %}
        </li>

        <span class="text-primary">
             第{{ supplier_list.number }}页   共{{ supplier_list.paginator.num_pages }}页
        </span>

        <li>
        {% if supplier_list.has_next %}
            <a href="?page={{ supplier_list.next_page_number }}">下一页</a>
        {% else %}
            <a> 最后一页 </a>
        {% endif %}

        </li>
      </ul>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>